"""Defines environment for proposition proof task"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Sequence, List, Tuple

from .elem import (
    Sequent, Rule,
    And, Or, Implies,
    Axiom, ImpliesRight, ImpliesLeft,
    AndRight, AndLeft,
    OrRight1, OrRight2, OrLeft,
    TrueRight, FalseLeft,
)


# =============================================================================
# Proof Node Types
# =============================================================================

@dataclass
class ProofNode:
    """Base class for proof tree nodes."""
    sequent: Sequent
    
    @property
    def is_provable(self) -> bool:
        """Whether this node represents a provable sequent."""
        raise NotImplementedError
    
    @property
    def depth(self) -> int:
        """Maximum depth of the proof tree rooted at this node."""
        return 1
    
    @property
    def size(self) -> int:
        """Total number of nodes in the tree rooted at this node."""
        return 1


@dataclass
class CompletedProofNode(ProofNode):
    """A sequent proven by an axiom-like rule (no subgoals needed)."""
    rule: Rule
    
    @property
    def is_provable(self) -> bool:
        return True
    
    def __str__(self) -> str:
        return f"{self.sequent}  [✓ {self.rule}]"


@dataclass
class FailedProofNode(ProofNode):
    """A sequent that could not be proven."""
    reason: str = ""
    
    @property
    def is_provable(self) -> bool:
        return False
    
    def __str__(self) -> str:
        reason_str = f": {self.reason}" if self.reason else ""
        return f"{self.sequent}  [✗{reason_str}]"


@dataclass
class InternalProofNode(ProofNode):
    """A node with rule applications leading to child proof nodes.
    
    Each branch is a (rule, children) pair where children are the proof nodes
    for each subgoal generated by that rule application.
    """
    branches: List[Tuple[Rule, List[ProofNode]]] = field(default_factory=list)
    
    @property
    def is_provable(self) -> bool:
        """Provable if any branch has all children provable."""
        return any(
            all(child.is_provable for child in children)
            for rule, children in self.branches
        )
    
    @property
    def depth(self) -> int:
        if not self.branches:
            return 1
        max_child_depth = max(
            max((child.depth for child in children), default=0)
            for rule, children in self.branches
        )
        return 1 + max_child_depth
    
    @property
    def size(self) -> int:
        return 1 + sum(
            sum(child.size for child in children)
            for rule, children in self.branches
        )
    
    def successful_branch(self) -> Tuple[Rule, List[ProofNode]] | None:
        """Return the first branch where all children are provable, or None."""
        for rule, children in self.branches:
            if all(child.is_provable for child in children):
                return (rule, children)
        return None
    
    def __str__(self) -> str:
        return self._to_string(indent=0)
    
    def _to_string(self, indent: int = 0) -> str:
        prefix = "  " * indent
        lines = [f"{prefix}{self.sequent}"]
        for rule, children in self.branches:
            provable = all(c.is_provable for c in children)
            mark = "✓" if provable else "✗"
            lines.append(f"{prefix}  [{mark} {rule}]")
            for child in children:
                if isinstance(child, InternalProofNode):
                    lines.append(child._to_string(indent + 2))
                else:
                    lines.append(f"{prefix}    {child}")
        return "\n".join(lines)


# =============================================================================
# Rule Generation
# =============================================================================

def get_next_rules(sequent: Sequent) -> Sequence[Rule]:
    """Generate applicable rules for a sequent"""
    rules: List[Rule] = [Axiom(), TrueRight(), FalseLeft()]
    
    # left rules
    for ant in sequent.ants:
        if isinstance(ant, And):
            rules.append(AndLeft(ant))
        if isinstance(ant, Or):
            rules.append(OrLeft(ant))
        elif isinstance(ant, Implies):
            rules.append(ImpliesLeft(ant))
    
    # right rules
    if isinstance(sequent.cons, Implies):
        rules.append(ImpliesRight())
    elif isinstance(sequent.cons, And):
        rules.append(AndRight())
    elif isinstance(sequent.cons, Or):
        rules.append(OrRight1())
        rules.append(OrRight2())
    
    return rules


# =============================================================================
# Proof Search
# =============================================================================

def build_proof_tree(
    sequent: Sequent,
    max_depth: int = 10_000,
) -> ProofNode:
    """Build a complete proof tree exploring all rule applications.
    
    Returns a ProofNode representing the full search tree. Use `.is_provable`
    to check if a successful proof exists within the tree.
    """
    # Memoize per (sequent, depth) to reuse identical subtrees across branches.
    cache: dict[tuple[Sequent, int], ProofNode] = {}

    def build(seq: Sequent, depth: int) -> ProofNode:
        if depth <= 0:
            return FailedProofNode(seq, reason="depth limit")
        key = (seq, depth)
        if key in cache:
            return cache[key]

        branches: List[Tuple[Rule, List[ProofNode]]] = []

        for rule in get_next_rules(seq):
            result = rule.apply(seq)
            if result is None:
                continue  # Rule not applicable

            if len(result) == 0:  # Empty list = proven immediately
                node = CompletedProofNode(seq, rule)
                cache[key] = node
                return node

            # Build proof nodes for all subgoals
            children = [build(subgoal, depth - 1) for subgoal in result]
            branches.append((rule, children))

        if not branches:
            node = FailedProofNode(seq, reason="no applicable rules")
        else:
            node = InternalProofNode(seq, branches)

        cache[key] = node
        return node

    return build(sequent, max_depth)
